default_language_version:
  python: python3.10

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args:
          - --maxkb=1024
      - id: debug-statements
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.7
    hooks:
      - id: uv-lock

  - repo: https://github.com/johannsdg/pre-commit-license-headers
    rev: v0.1.0
    hooks:
      - id: check-license-headers
        files: ^src/.*\.py$
        exclude: ^src/praxis_remote/proto/.*_pb2(_grpc)?\.py$
        args:
          - --template
          - |
            SPDX-FileCopyrightText: [YEARS] [OWNER]
            SPDX-License-Identifier: Apache-2.0
          - --owner=.+

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.1
    hooks:
      - id: ruff
        args:
          - --fix
          - --exit-non-zero-on-fix
      - id: ruff-format

  - repo: https://github.com/adhtruong/mirrors-typos
    rev: v1.38.1
    hooks:
      - id: typos
        args:
          - --force-exclude

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.0
    hooks:
      - id: pyupgrade
        args:
          - --py310-plus
        exclude: ^src/praxis_remote/proto/.*_pb2(_grpc)?\.py$

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks
